* lucy :_mo_:
  :PROPERTIES:
  :DATE: [2014-11-09 Sun]
  :ID:       7E8B5542-122F-4C00-B3F7-EF0B8790F383
  :END:

读了和菜头在公众号的影评，我去看了《超体》。我没有绝妙的文笔评价这部电影，但仍想写写喜欢它的原因。

我知道一些观众对《超体》有些失望，他们的评价是虎头蛇尾。因为整部电影铺陈了很长时间，似乎是在设置一个悬念：当人的大脑利用率达到100%时，将会发生什么？可是当100%到来的那一刻，电影戛然而止。

在我看来，故事到了这里，精彩的部分已经演完了，更精彩的留给观众去想象。

本片的精彩之处，不在于一个弱女子因为意外获得了超能力而产生逆袭，如果是这样，它和一般的超人电影有什么区别？相反，这部电影最打动我的地方，是它背后蕴含的思想：生存的意义、生命进化的过程、时间等等关于生存本质的宏大问题。

人性本身是自私而愚蠢的，摩根·弗里曼饰演的教授担心这样的人类掌握了更多的知识后，会发生不好的事情。他从技术上预测当大脑利用率达到20%时，人将开始能操纵物质乃至操纵他人，但是预测仅此为止，他也无法想象那时的人类会变成什么样。然而，他的担心是多余的，斯嘉丽·约翰逊所饰的Lucy没有变『坏』，当她明白自己身上发生的变化时，她打电话向母亲描述自己的感受：她能回忆起自己的每一处记忆，她已经没有了痛苦、恐惧和欲望，她感到万物是一体的。打电话这一段让我十分感动，这一刻的Lucy已经成了佛陀，或者，佛陀就是大脑利用率提高了的印度王子。她的感受并非不能理解，痛苦、恐惧和欲望本就是基因趋利避害的生理机制，当她能观照自己的每一个细胞时，基因的小把戏怎可能继续得逞呢？

Lucy证明了人类的希望：进化本身是残酷无情的，因为只有努力竞争才能生存下去，但是当进化达到一定高度时，人已经能有所察觉从而超越基因的控制，有意识的选择生命的方向。Lucy感到自己生命所剩不多时，向教授请教该做些什么。教授说，生命一代代的传承，使上一代的经验传给下一代，也许你应该把自己的知识传播出去。Lucy用生命最后的能量，把所有的知识变成了一台计算机，留给了人类。

警察最后问道，Lucy在哪里呢？Lucy说，我无所不在。为什么说无所不在？因为她的知识、她的经验已经留下来了，成为了人类的一部分，随着人类对世界的改造，也将成为世界的一部分。这就是人类生命意义的升华：生命不再以基因本身的留存为目的，而是为了促成生命整体对宇宙的探索。

这样说来，我们对生命和死亡是不是有了新的理解？我们的先人没有逝去，他们寄存的肉体消失了，但他们的探索和发现仍然在影响着世界，他们的经验是我们今日生活的基础，我们的经验将是未来人类的基础。从那只叫Lucy的猿人，到大草原上的印第安人，到工业革命时匆匆走过的路人，如此代代传承，生命离他们所探寻的未知之地将越来越近。

Lucy最后制造计算机时，屋外还在进行着激烈的厮杀。可是和屋里纯白的超然环境相比，这场厮杀已经没有了批判的必要，就像我们看动物世界中猎豹追杀羚羊一样，已经成了进化史中的自然现象，谁胜谁负又有什么关系。因为生命有了更高层级的视角，对这种厮杀也就有了一种悲悯。

电影放映时，我经常想到《三体》、佛教以及《自私的基因》，这样的思绪缠绕使我沉浸在电影引发的哲学思考中，科幻、打斗、剧情已经成了细枝末节，我想，导演已经成功了。

影片最后问道，现在，你想用你的时间做什么呢？这是留给每个人的问题。
