* book review smart era                                                :_mo_:
  :PROPERTIES:
  :ID:       B35184F3-DDA1-4E57-BC18-674CE42DAFBB
  :DATE: [2016-11-06]
  :END:

很长时间没买纸质书了，最近对人工智能的关注开始增多，就读了吴军博士的《智能时代》和《硅谷之谜》，简单记录下感受。

** 《智能时代》
《智能时代》从工业革命、产业变迁的高度描述了正在到来的大数据、机器智能时代
。

印象深刻的几点：

1. 数据的重要性

  《万历十五年》中的一个重要观点是，明代的中国不能实现数目字管理，整个国家的治理混乱。而智能时代正好是这种情况的反面：科技、经济、社会治理的各项活动产生数据，从数据中抽象出信息和知识。

2. 智能时代蕴含着机械思维向大数据思维的转变

  随着系统变得复杂，因果性越来越难以寻找，而数据为发现相关性提供了途径。人从利用因果性变为利用相关性，尽管相关性有时难以解释，但对解决许多问题是有效的。

3. 智能时代对社会和产业的变革性影响。

  医疗、制药、法律、新闻等行业，都会被智能时代的先进技术改变。前一段时间特斯拉放出了最新的无人驾驶效果视频，令人惊叹：轿车自动行驶至目的地后，「驾驶员」下车离去，车辆自动寻找停车位并停放好自己。不需要太大胆的预测也能想到，5到10年内，人类驾驶员的作用将会逐渐淡化。

4. 负面影响

  科技是一把双刃剑。智能时代和人类历次工业变革一样，也会给社会带来阵痛。比如，人工智能带来的自动化水平提高将取代许多人的工作，这样就业问题如何解决呢？供给侧改革后能源行业的工人还可以改行开专车，而自动驾驶成熟后，他们连这样的去处也少了一个。

  反应快、运气好的人还可以努力做下个时代前2%的人，但那些失落者是否会被时代抛弃？如果真的出现大量失业，或者造成社会鸿沟加剧，社会能否消化造成的影响？科技水平的提高，也应该伴随着人文水平、道德水平的提高。这些问题，需要未雨绸缪地做准备。

5. 解决问题的小例子

  吴军博士提到了在谷歌做搜索引擎自动回答问题的工程方法，看似复杂的智能问题，分步骤用数据的方式解决，有一些启发性。如果有些智能问题难以解决，先用不那么高大上的方法做一个方案出来，也可以解决一定比例的问题，不用憋在原地寻找完备性。

** 《硅谷之谜》

读过《浪潮之巅》的读者对这本书的话题不会陌生，相比前者，本书在理论上做了更多的升华总结，特别是从文化和思想层面解读了硅谷的独特之处。看不到硅谷的这一层先进之处，再造硅谷的尝试也许只能是『学我者病』。

全书的逻辑结构很清晰：
#+BEGIN_EXAMPLE
硅谷有多牛->
其他人是怎么分析硅谷牛的原因的->
硅谷历史回顾->
指出硅谷的独特之处->
升华到科学思想层面，对比机械和信息时代的不同。
#+END_EXAMPLE

务虚的思考表面上离实际工作有距离，其实不然。新的思想方式、企业制度正是生产关系对生产力的适应。参照书中的理论和现实经验，IT从业者至少可以试着判断什么样的公司（团队）是靠谱的，以及如何管理团队，如何合作。
